/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { UserInterface, UserInterfaceInterface } from "../UserInterface";

const _abi = [
  {
    inputs: [],
    name: "trust_rating",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class UserInterface__factory {
  static readonly abi = _abi;
  static createInterface(): UserInterfaceInterface {
    return new utils.Interface(_abi) as UserInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UserInterface {
    return new Contract(address, _abi, signerOrProvider) as UserInterface;
  }
}
