/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Paper } from "./Paper";
export type { PeerReview } from "./PeerReview";
export type { User } from "./User";

export { Paper__factory } from "./factories/Paper__factory";
export { PeerReview__factory } from "./factories/PeerReview__factory";
export { User__factory } from "./factories/User__factory";
