/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface UserInterface extends ethers.utils.Interface {
  functions: {
    "deployPaper(string)": FunctionFragment;
    "getPaper(address)": FunctionFragment;
    "getPapers()": FunctionFragment;
    "papers(address)": FunctionFragment;
    "papers_array(uint256)": FunctionFragment;
    "peer_review_address()": FunctionFragment;
    "setTrustRating(uint256)": FunctionFragment;
    "trust_rating()": FunctionFragment;
    "user_address()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "deployPaper", values: [string]): string;
  encodeFunctionData(functionFragment: "getPaper", values: [string]): string;
  encodeFunctionData(functionFragment: "getPapers", values?: undefined): string;
  encodeFunctionData(functionFragment: "papers", values: [string]): string;
  encodeFunctionData(
    functionFragment: "papers_array",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "peer_review_address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustRating",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "trust_rating",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "user_address",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "deployPaper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPaper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPapers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "papers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "papers_array",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "peer_review_address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustRating",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trust_rating",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "user_address",
    data: BytesLike
  ): Result;

  events: {};
}

export class User extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: UserInterface;

  functions: {
    deployPaper(
      _ipfsHash: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getPaper(
      _paperAddress: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getPapers(
      overrides?: CallOverrides
    ): Promise<[string[]] & { _address: string[] }>;

    papers(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    papers_array(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    peer_review_address(overrides?: CallOverrides): Promise<[string]>;

    setTrustRating(
      _trust_rating: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    trust_rating(overrides?: CallOverrides): Promise<[BigNumber]>;

    user_address(overrides?: CallOverrides): Promise<[string]>;
  };

  deployPaper(
    _ipfsHash: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getPaper(_paperAddress: string, overrides?: CallOverrides): Promise<string>;

  getPapers(overrides?: CallOverrides): Promise<string[]>;

  papers(arg0: string, overrides?: CallOverrides): Promise<string>;

  papers_array(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  peer_review_address(overrides?: CallOverrides): Promise<string>;

  setTrustRating(
    _trust_rating: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  trust_rating(overrides?: CallOverrides): Promise<BigNumber>;

  user_address(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    deployPaper(_ipfsHash: string, overrides?: CallOverrides): Promise<string>;

    getPaper(_paperAddress: string, overrides?: CallOverrides): Promise<string>;

    getPapers(overrides?: CallOverrides): Promise<string[]>;

    papers(arg0: string, overrides?: CallOverrides): Promise<string>;

    papers_array(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    peer_review_address(overrides?: CallOverrides): Promise<string>;

    setTrustRating(
      _trust_rating: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    trust_rating(overrides?: CallOverrides): Promise<BigNumber>;

    user_address(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    deployPaper(
      _ipfsHash: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getPaper(
      _paperAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPapers(overrides?: CallOverrides): Promise<BigNumber>;

    papers(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    papers_array(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    peer_review_address(overrides?: CallOverrides): Promise<BigNumber>;

    setTrustRating(
      _trust_rating: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    trust_rating(overrides?: CallOverrides): Promise<BigNumber>;

    user_address(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    deployPaper(
      _ipfsHash: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getPaper(
      _paperAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPapers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    papers(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    papers_array(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    peer_review_address(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setTrustRating(
      _trust_rating: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    trust_rating(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    user_address(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
